# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('fecha_alta', models.DateField(auto_now=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(max_length=90)),
                ('celular', models.CharField(blank=True, max_length=90, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('es_socio', models.BooleanField()),
                ('profesion', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.CharField(blank=True, editable=False, max_length=90, null=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=19)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('usuario', models.CharField(blank=True, editable=False, max_length=90, null=True)),
            ],
            options={
                'db_table': 'caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id_concepto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('usuario', models.CharField(blank=True, editable=False, max_length=90, null=True)),
            ],
            options={
                'db_table': 'concepto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('id_concepto_pago_asoc', models.IntegerField(blank=True, null=True)),
                ('id_concepto_pago_insc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.CharField(blank=True, editable=False, max_length=90, null=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamenCurso',
            fields=[
                ('id_examen_curso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_examen', models.DateField()),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('usuario', models.CharField(blank=True, editable=False, max_length=90, null=True)),
            ],
            options={
                'db_table': 'examen_curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'idioma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_alta', models.DateField(auto_now=True, null=True)),
                ('fecha_pago_insc', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inscripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoInscCuota',
            fields=[
                ('id_pago_insc_cuota', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField()),
                ('es_socio', models.IntegerField()),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('fecha_cuota', models.DateField()),
                ('pagado', models.IntegerField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, editable=False, max_length=90, null=True)),
            ],
            options={
                'db_table': 'pago_insc_cuota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoCurso',
            fields=[
                ('id_periodo_curso', models.AutoField(primary_key=True, serialize=False)),
                ('cant_meses', models.IntegerField()),
                ('fecha_alta', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('importe_inscripcion', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'periodo_curso',
                'managed': False,
            },
        ),
    ]
